using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Nop.Plugin.Payments.Qualpay.Domain.PaymentGateway
{
    /// <summary>
    /// Represents base response from Qualpay Payment Gateway
    /// </summary>
    public abstract class PaymentGatewayResponse : QualpayResponse
    {
        #region Properties

        /// <summary>
        /// Gets or sets a unique identifier generated by the payment gateway for each transaction. 
        /// </summary>
        [JsonProperty(PropertyName = "pg_id")]
        public string TransactionId { get; set; }

        /// <summary>
        /// Gets or sets the response code from the Qualpay payment gateway
        /// </summary>
        [JsonProperty(PropertyName = "rcode")]
        [JsonConverter(typeof(StringEnumConverter))]
        public PaymentGatewayResponseCode? ResponseCode { get; set; }

        /// <summary>
        /// Gets or sets the response message text from the payment gateway application.
        /// </summary>
        [JsonProperty(PropertyName = "rmsg")]
        public string Message { get; set; }

        /// <summary>
        /// Gets or sets a field is returned by the tokenize message or when an authorization or sale message requests tokenization of the cardholder data.
        /// </summary>
        [JsonProperty(PropertyName = "card_id")]
        public string CardId { get; set; }

        /// <summary>
        /// Gets or sets field is returned when the message was sent to the card issuer for approval.
        /// </summary>
        [JsonProperty(PropertyName = "auth_code")]
        public string AuthorizationCode { get; set; }

        /// <summary>
        /// Gets or sets the result from the card issuer.
        /// </summary>
        [JsonProperty(PropertyName = "auth_cvv2_result")]
        public string Cvv2Result { get; set; }

        /// <summary>
        /// Gets or sets the result from the card issuer.
        /// </summary>
        [JsonProperty(PropertyName = "auth_avs_result")]
        public string AvsResult { get; set; }

        /// <summary>
        /// Gets or sets the collection of field data that will be echoed back in the response message.
        /// </summary>
        [JsonProperty(PropertyName = "echo_fields")]
        public IEnumerable<KeyValuePair<string, string>> CustomFields { get; set; }

        /// <summary>
        /// Gets or sets the transaction amount from the request message. 
        /// </summary>
        [JsonProperty(PropertyName = "amt_tran")]
        public decimal? Amount { get; set; }

        /// <summary>
        /// Gets or sets collection of the result of the batch close by currency and location
        /// </summary>
        [JsonProperty(PropertyName = "batch_info")]
        public IEnumerable<Batch> BatchInfo { get; set; }

        #endregion
    }
}