using System.Collections.Generic;
using Newtonsoft.Json;

namespace Nop.Plugin.Payments.Qualpay.Domain.Platform
{
    /// <summary>
    /// Represents base request to Qualpay Customer Vault
    /// </summary>
    public abstract class CustomerVaultRequest : PlatformRequest
    {
        #region Properties

        /// <summary>
        /// Gets os sets Unique ID established by merchant to identify a customer. The customer ID can be used to add subscriptions   using the Recurring Billing API or make payments using the Payment Gateway API. Once established, this ID cannot be udpated. It can contain upto 32 characters. It is case sensitive. Only letters and numbers are allowed in a Customer ID. 
        /// </summary>
        [JsonProperty(PropertyName = "customer_id")]
        public string CustomerId { get; set; }

        /// <summary>
        /// Gets os sets Unique Internal ID generated by Qualpay to identify a Vault Customer.
        /// </summary>
        [JsonProperty(PropertyName = "rec_id")]
        public long? RecordId { get; set; }

        /// <summary>
        /// Gets os sets The Node to which the merchant belongs. For Customer record, this refers to the Qualpay supplied Merchant ID.
        /// </summary>
        [JsonProperty(PropertyName = "node_id")]
        public long? MerchantId { get; set; }

        /// <summary>
        /// Gets os sets Customer's First Name. Can contain upto 32 characters.
        /// </summary>
        [JsonProperty(PropertyName = "customer_first_name")]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets os sets Customer's Last Name. Can contain upto 32 characters.
        /// </summary>
        [JsonProperty(PropertyName = "customer_last_name")]
        public string LastName { get; set; }

        /// <summary>
        /// Gets os sets Customer Business name if applicable. 
        /// </summary>
        [JsonProperty(PropertyName = "customer_firm_name")]
        public string Company { get; set; }

        /// <summary>
        /// Gets os sets Customer's Phone Number. Can contain upto 16 characters.
        /// </summary>
        [JsonProperty(PropertyName = "customer_phone")]
        public string Phone { get; set; }

        /// <summary>
        /// Gets os sets Customer's Email address. Can contain upto 64 characters.
        /// </summary>
        [JsonProperty(PropertyName = "customer_email")]
        public string Email { get; set; }

        /// <summary>
        /// Gets os sets Comments
        /// </summary>
        [JsonProperty(PropertyName = "comments")]
        public string Comments { get; set; }

        /// <summary>
        /// Gets os sets Default Card Number for this customer. This card number is used for subscription payments. 
        /// </summary>
        [JsonProperty(PropertyName = "primary_card_number")]
        public string PrimaryCardNumber { get; set; }

        /// <summary>
        /// Gets os sets an array of shipping addresses.
        /// </summary>
        [JsonProperty(PropertyName = "shipping_addresses")]
        public IEnumerable<ShippingAddress> ShippingAddresses { get; set; }

        /// <summary>
        /// Gets os sets an array of Billing Cards.
        /// </summary>
        [JsonProperty(PropertyName = "billing_cards")]
        public IEnumerable<BillingCard> BillingCards { get; set; }

        #endregion
    }
}