using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Nop.Plugin.Payments.Qualpay.Domain.Platform
{
    /// <summary>
    /// Represents base request to webhook resources
    /// </summary>
    public abstract class WebhookRequest : PlatformRequest
    {
        #region Properties

        /// <summary>
        /// Gets or sets unique ID generated by Qualpay to identify a webhook
        /// </summary>
        [JsonProperty(PropertyName = "webhook_id")]
        public long? WebhookId { get; set; }

        /// <summary>
        /// Gets or sets the node at which the webhook will be created. If a merchant id is sent in this field, the webhook is created for the merchant. If a webhook_node is not included in the request, the webhook will be created at the api key's node. 
        /// </summary>
        [JsonProperty(PropertyName = "webhook_node")]
        public string WebhookNode { get; set; }

        /// <summary>
        ///  Status of the webhook.
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        [JsonConverter(typeof(StringEnumConverter))]
        public WebhookStatus? Status { get; set; }

        /// <summary>
        /// Gets or sets a label to identify the webhook
        /// </summary>
        [JsonProperty(PropertyName = "label")]
        public string Label { get; set; }

        /// <summary>
        /// Gets or sets the webhook endpoint to which requests will be posted. The endpoint must use HTTPs and should serve HTTP POST requests. The endpoint URL should respond with an HTTP 2xx response. Any other HTTP response message is considered a failure and Qualpay will retry posting the same request until a successful response is received or the request expires, whichever comes first. 
        /// </summary>
        [JsonProperty(PropertyName = "notification_url")]
        public string NotificationUrl { get; set; }

        /// <summary>
        /// Gets or sets an array of email addresses that will be notified when a webhook is suspended.
        /// </summary>
        [JsonProperty(PropertyName = "email_address")]
        public IEnumerable<string> EmailAddress { get; set; }

        /// <summary>
        /// Gets or sets an array of events that will trigger the POST request.
        /// </summary>
        [JsonProperty(PropertyName = "events")]
        public IEnumerable<string> Events { get; set; }

        /// <summary>
        /// Gets or sets webhook creation timestamp in YYYY-MM-DD HH:mm:ss format
        /// </summary>
        [JsonProperty(PropertyName = "db_timestamp")]
        public string DbTimestamp { get; set; }

        /// <summary>
        /// Gets or sets a secret that will be used by Qualpay to generate the x-qualpay-webhook-signature header. Qualpay signs each webhook request using the x-qualpay-webhook-signature header. This signature can be used to validate that a request is initiated by Qualpay.  The signature is a Base 64 encoded HMAC-256 digest generated from the request payload using the webhook’s secret.This secret can be viewed only when adding a webhook. Use Qualpay manager to change the secret. 
        /// </summary>
        [JsonProperty(PropertyName = "secret")]
        public string Secret { get; set; }

        #endregion
    }
}